### ISSUE TITLE
add folder  structure to readme to better understand the dataset 

### ISSUE THREAD

**Issue by Lohith-Loke** [Lohith-Loke/leaf-image-dataset#1]
need a proper discription for folder structure to make it easier to understand the directories 
reffer to **tree**  a linux file explorer

**Comment by g33tansh** [comment]
Correct me if I'm wrong. I need to make a structure similar to the following for the given dataset?

```
project
│   README.md
│   file001.txt    
│
└───folder1
│   │   file011.txt
│   │   file012.txt
│   │
│   └───subfolder1
│       │   file111.txt
│       │   file112.txt
│       │   ...
│   
└───folder2
    │   file021.txt
    │   file022.txt
```

And am I supposed to display the names of the images as well or just the directories?

**Comment by Lohith-Loke** [comment]
yes it is 
you can use tree command as it is to get the text  
or a shell script that does the same

**Comment by g33tansh** [comment]
Alright I'll use the tree command and one more doubt. Am I supposed to display the names of the images as well or just the directories? Also please assign me this issue. 
Thanks!

**Comment by Lohith-Loke** [comment]
names of images is not required just folder with names of plant leafs
use folder ''leaf-image-dataset/New Plant Diseases Dataset(Augmented)/" as root

**Comment by g33tansh** [comment]
Hey @Lohith-Loke, there is a typo in the spelling of hacktoberfest in the repository's tags. Please make the necessary changes.
Thank you!

**Comment by Lohith-Loke** [comment]
tags are corrrect 

ping me on linked in [here](https://www.linkedin.com/in/lohith-n-9ba565221)
if there are any more clarification needed
